image: mcr.microsoft.com/dotnet/sdk:5.0

stages:
  - build

build:
  stage: build
  script:
    - dotnet restore RabbitSignalrNotifications/RabbitSignalrNotifications.sln --locked-mode
    - dotnet build RabbitSignalrNotifications/RabbitSignalrNotifications.sln -c Release --no-restore --no-dependencies