name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    types: [closed]
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore
        run: dotnet restore RabbitSignalrNotifications.sln --locked-mode
      - name: Build
        run: dotnet build RabbitSignalrNotifications.sln -c Release --no-restore